# configuracion de puerto
server.port=8080
# Profile Activo
spring.profiles.active=@activated.profile@

# Configuración de JPA/Hibernate
# Open Session in View (OSIV). Deshabilitar para evitar problemas de rendimiento y seguridad en producción
spring.jpa.open-in-view=false
