# configuracion de puerto
server.port=8080
# Profile Activo
spring.profiles.active=@activated.profile@

# Configuración de JPA/Hibernate
# Open Session in View (OSIV). Deshabilitar para evitar problemas de rendimiento y seguridad en producción
spring.jpa.open-in-view=false

#Configuracion TimeZone
spring.jackson.time-zone=America/Mexico_City
spring.jackson.locale=es_MX

#Configuracion logs error
server.error.whitelabel.enabled=false

#Configuracion health
management.health.db.enabled=true
management.health.ldap.enabled=false
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=estatus
management.endpoints.web.path-mapping.metrics=metricas
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.roles=ADMIN
management.endpoint.health.show-details=when_authorized

# Desactiva el manejo automatico de recursos estaticos
spring.web.resources.add-mappings=false
